language: node_js
dist: trusty
# addons:
#   apt:
#     packages:
#       # This is required to run new chrome on old trusty
#       - libnss3
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
